export const INITIALIZE = "INITIALIZE";
export type INITIALIZE = typeof INITIALIZE;
export const UPDATEFONTSIZE = "UPDATEFONTSIZE";
export type UPDATEFONTSIZE = typeof UPDATEFONTSIZE;
export const UPDATEFAV = "UPDATEFAV";
export type UPDATEFAV = typeof UPDATEFAV;
export const ADDCUSTOM = "ADDCUSTOM";
export type ADDCUSTOM = typeof ADDCUSTOM;
export const DELETEITEM = "DELETEITEM";
export type DELETEITEM = typeof DELETEITEM;
export const SEARCHINPUT = "SEARCHINPUT";
export type SEARCHINPUT = typeof SEARCHINPUT;
export const UPDATEDATA = "UPDATEDATA";
export type UPDATEDATA = typeof UPDATEDATA;
export const ADDLOCAL = "ADDLOCAL";
export type ADDLOCAL = typeof ADDLOCAL;

export const ISDARK = "ISDARK";
export type ISDARK = typeof ISDARK;
